# Site settings
title:          flyer0126
description:    "flyer0126 github page"
#baseurl:        "/tale"
url:            "https://flyer0126.github.io"

# Author
author:
  name:         flyer0126
  url:          https://chester.how
  email:        flyer0126@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
